/**
 * Generates `src/animation/__tests__/fixtures/keyframe-eval-parity.json` —
 * the cross-language contract for keyframe EVALUATION (round 47).
 *
 * The TS engine is the source of truth for what an animated value is at a
 * given tick (`getScalarChannelValueAtTime`: sort, clamp handles, hold /
 * linear / bezier segments, edge extrapolation, 20-iteration bisection for
 * bezier time). The native exporters re-implement that function — Swift
 * `KeyframeEvaluator.swift`, Kotlin `KeyframeEvaluator.kt` — because the
 * exported file must place a keyframed clip exactly where the preview did.
 * This fixture is how each port proves it: channels in the EDL's own
 * flattened shape (`EdlAnimationChannel`, what the natives actually parse)
 * plus the value the engine computes at a spread of sample ticks.
 *
 * Run from packages/editor-core:
 *   bun --preload ./src/test-support/wasm-preload.ts scripts/generate-keyframe-parity-fixture.ts
 *
 * `__tests__/keyframe-eval-parity.test.ts` re-derives every expectation and
 * fails if the checked-in file drifts from the engine.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getScalarChannelValueAtTime } from "../src/animation/interpolation";
import {
	buildParityChannels,
	parityChannelToScalarChannel,
	paritySampleTicks,
} from "../src/animation/__tests__/keyframe-parity-cases";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, "../src/animation/__tests__/fixtures/keyframe-eval-parity.json");

const channels = buildParityChannels();
const samples = channels.flatMap((channel, channelIndex) => {
	const scalar = parityChannelToScalarChannel({ channel });
	return paritySampleTicks({ channel }).map((timeTicks) => ({
		channel: channelIndex,
		timeTicks,
		expected: getScalarChannelValueAtTime({ channel: scalar, time: timeTicks, fallbackValue: Number.NaN }),
	}));
});

const fixture = {
	$comment:
		"GENERATED by scripts/generate-keyframe-parity-fixture.ts — do not hand-edit. Channels are EdlAnimationChannel-shaped; `expected` is the TS engine's getScalarChannelValueAtTime at `timeTicks`. Swift/Kotlin evaluators must match every sample to 1e-6.",
	tolerance: 1e-6,
	channels,
	samples,
};

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${JSON.stringify(fixture, null, "\t")}\n`);
console.log(`wrote ${outPath}: ${channels.length} channels, ${samples.length} samples`);
