"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import "@cutlyra/mobile-ui/tokens.css";
import "@cutlyra/mobile-ui/components.css";
import {
	TimelineView,
	generateStressProject,
	STRESS_PROJECT_CLIP_COUNT,
	STRESS_PROJECT_TRACK_COUNT,
	type TimelineViewHandle,
} from "@cutlyra/mobile-ui";

/**
 * M7 dev harness — the CapCut-mobile timeline surface, driven by a
 * SYNTHETIC project matching plan M7's own exit-criterion stress scenario
 * ("a 20-clip, 5-track, 10-minute project"). Not a production route;
 * visual + interaction + rough perf QA only. Reachable at /dev/mobile-timeline.
 *
 * NOT DONE this session: wiring this to a real `EditorCore` project via
 * `useEditor()` (mapping the live scene graph into `TimelineProjectVM`).
 * Everything rendered here is generated by
 * packages/mobile-ui/src/timeline/mock-data.ts. See the M7 handoff notes
 * for what a real integration needs to do at that boundary.
 *
 * The plan's exit criterion asks for "60fps (p95 frame time <=16.7ms)...
 * measured with platform profilers" on a real mid-tier device — that was
 * NOT measured this session (no device/simulator was used for this
 * milestone). What WAS checked here, in a real desktop Chrome tab: the
 * component renders without console errors, interactions (select/trim/
 * pinch-zoom-via-wheel/transition-sheet) work, and the "rendered clip DOM
 * nodes" counter below proves virtualization is actually excluding
 * off-screen clips rather than just claiming to.
 */
export default function MobileTimelineHarnessPage() {
	const project = useMemo(() => generateStressProject(), []);
	const timelineRef = useRef<TimelineViewHandle>(null);
	const [currentTimeSec, setCurrentTimeSec] = useState(0);
	const [zoomPct, setZoomPct] = useState(100);
	const [isPlaying, setIsPlaying] = useState(false);
	const [renderedClipCount, setRenderedClipCount] = useState<number | null>(null);
	const playIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
	const currentTimeSecRef = useRef(0);
	useEffect(() => {
		currentTimeSecRef.current = currentTimeSec;
	}, [currentTimeSec]);

	const togglePlay = () => {
		if (isPlaying) {
			if (playIntervalRef.current) clearInterval(playIntervalRef.current);
			playIntervalRef.current = null;
			setIsPlaying(false);
			return;
		}
		setIsPlaying(true);
		playIntervalRef.current = setInterval(() => {
			// `seek()` has its own side effects (mutates TimelineView's scroll
			// position) — calling it from INSIDE the setCurrentTimeSec updater
			// below was a real bug this session (React logged "Cannot update a
			// component while rendering a different component," confirmed via
			// the browser console): a functional updater must stay pure, since
			// React can invoke it outside normal event-handler timing. Reading
			// `currentTimeSecRef.current` here and calling `seek` as a
			// top-level statement in this setInterval callback (not nested
			// inside the updater) keeps both calls in ordinary event-handler
			// timing instead.
			const next = currentTimeSecRef.current + 0.5;
			if (next >= project.durationSec) {
				if (playIntervalRef.current) clearInterval(playIntervalRef.current);
				playIntervalRef.current = null;
				setIsPlaying(false);
				timelineRef.current?.seek({ timeSec: project.durationSec });
				return;
			}
			// seek()'s own onTimeChange callback (below) is what updates
			// currentTimeSec — no separate setCurrentTimeSec call needed here.
			timelineRef.current?.seek({ timeSec: next });
		}, 100);
	};

	const countRenderedClips = () => {
		const nodes = document.querySelectorAll(
			"[data-mobile-timeline-harness] .cc-timeline__clip",
		);
		setRenderedClipCount(nodes.length);
	};

	return (
		<div
			style={{
				minHeight: "100vh",
				background: "#0b0b0b",
				display: "flex",
				flexDirection: "column",
				alignItems: "center",
				gap: 16,
				padding: 24,
				fontFamily: "system-ui, sans-serif",
				color: "#ddd",
			}}
		>
			<div style={{ maxWidth: 600, fontSize: 13, lineHeight: 1.5 }}>
				<h1 style={{ fontSize: 18, marginBottom: 4 }}>@cutlyra/mobile-ui — M7 timeline harness</h1>
				<p style={{ opacity: 0.7 }}>
					Synthetic {STRESS_PROJECT_CLIP_COUNT}-clip, {STRESS_PROJECT_TRACK_COUNT}-track,{" "}
					{Math.round(project.durationSec / 60)}-minute project — plan M7&apos;s own
					exit-criterion stress scenario. Scroll/drag the timeline to scrub (the fixed
					cyan line at center is the playhead; the content scrolls under it). Pinch
					(trackpad pinch or two-finger touch) to zoom. Tap a clip to select it, then
					drag its edges to trim. Tap the white square between main-track clips for the
					transition sheet.
				</p>
			</div>

			<div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
				<button type="button" onClick={togglePlay} style={buttonStyle}>
					{isPlaying ? "Pause" : "Play"}
				</button>
				<button
					type="button"
					onClick={() => {
						setCurrentTimeSec(0);
						timelineRef.current?.seek({ timeSec: 0 });
					}}
					style={buttonStyle}
				>
					Seek to 0
				</button>
				<button
					type="button"
					onClick={() => {
						timelineRef.current?.seek({ timeSec: project.durationSec / 2 });
					}}
					style={buttonStyle}
				>
					Seek to middle
				</button>
				<button type="button" onClick={countRenderedClips} style={buttonStyle}>
					Count rendered clip DOM nodes
				</button>
				<span style={{ fontSize: 12, opacity: 0.8 }}>
					t={currentTimeSec.toFixed(1)}s / {project.durationSec}s · zoom={zoomPct}% ·{" "}
					{renderedClipCount !== null
						? `${renderedClipCount}/${STRESS_PROJECT_CLIP_COUNT} clip nodes in DOM`
						: "click the count button after scrolling"}
				</span>
			</div>

			<div
				data-cutlyra-theme="capcut-mobile"
				data-mobile-timeline-harness
				style={{
					width: 390,
					height: 300,
					background: "var(--cc-bg-base)",
					borderRadius: 16,
					overflow: "hidden",
					boxShadow: "0 0 0 1px rgba(255,255,255,0.08)",
				}}
			>
				<TimelineView
					ref={timelineRef}
					project={project}
					onTimeChange={({ timeSec }) => setCurrentTimeSec(timeSec)}
					onZoomChange={({ zoom }) => setZoomPct(Math.round(zoom * 100))}
				/>
			</div>

			<p style={{ maxWidth: 600, fontSize: 12, opacity: 0.6 }}>
				This 390px-wide box is only the pixel-fidelity check. Virtualization matters
				most at low zoom where many clips exist off-screen horizontally and when
				scrolled deep into the 10-minute duration — try &quot;Seek to middle&quot;,
				zoom out (ctrl/cmd+scroll or pinch), then click the DOM-node-count button
				again.
			</p>
		</div>
	);
}

const buttonStyle: React.CSSProperties = {
	background: "#202020",
	color: "#f5f5f5",
	border: "1px solid #383838",
	borderRadius: 8,
	padding: "6px 12px",
	fontSize: 13,
	cursor: "pointer",
};
